name: heroku-deploy-stop-start

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      actions:
        description: "deploy/stop/start"
        default: "deploy"

jobs:
  heroku-deploy:
    if: ${{ github.event.inputs.actions == 'deploy' || github.event.inputs.actions == ''}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.roadto2.herokuapp.com/}}
          heroku_app_name: ${{secrets.roadto2}} #Must be unique in Heroku
          heroku_email: ${{secrets.qq2226972395@gmail.com}}
          usedocker: true
          # docker_build_args: |
          #   HD_UUID
        env:
          # 这是为了heroku，注意前缀有个HD，这是为了告诉heroku-deploy，这些变量需要传入到container 中。
          HD_UUID: ${{ secrets.31a7488c-70e1-41cf-8c62-68b2da79f551 }} # UUID for v2ray user, 为了安全，一定要放入github action token中
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.20020709chjdmm}}
  stop-start:
    if: ${{ github.event.inputs.actions  == 'start' || github.event.inputs.actions  == 'stop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.secrets.roadto2.herokuapp.com}}
          heroku_app_name: ${{secrets.roadto2}} #Must be unique in Heroku
          heroku_email: ${{qq2226972395@gmail.com}}
          justlogin: true
      - run: |
          echo action is ${{ github.event.inputs.actions }}
          if [[ ${{ github.event.inputs.actions }} == 'stop' ]]; then heroku ps:scale web=0 -a ${{secrets.roadto2}} && echo "stop"; fi
          if [[ ${{ github.event.inputs.actions }} == 'start' ]]; then heroku ps:scale web=1 -a ${{secrets.roadto2}} && echo "start"; fi
          heroku ps -a ${{secrets.roadto2}}
